### ISSUE TITLE
"Highlight Unavailable" Issues Flagged By AIFA

### ISSUE THREAD

**Issue by daphneyyt** [microsoft/accessibility-insights-for-android-service#89]
Hi, I have a follow-up question from the issue I posted previously: [See link, Question 2 on Highlights Unvailable](https://github.com/microsoft/accessibility-insights-for-android-service/issues/67)

Our client got back to us with regard to a 'highlight unavailable' issue detected by Accessibility Insights. We had previously advised our client to check their codes for accessibility issues and to rectify them. The client's developers was unable to locate these issues. Please see screenshots below for their comments. We would like to seek some advice on what the developers should do for their next steps to rectify the following issues:

**Issue 1:**
![Issue 1](https://user-images.githubusercontent.com/75086091/112787570-612b1780-908b-11eb-9cb6-476fd8f97787.png)

**Client's comment:**
The view here is not visible so it will not impact accessibility target users. We are not detecting any error so please clarify the image object that is causing this issue.

**Daphne's question to Microsoft:**
We were unable to advise on the specific location flagged by Accessibility Insight for the WCAG error captured due to unavailable highlights. Is it safe to assume that if a view is not visible, users who rely on accessibility tools will not be impacted? We believe the client's developers have checked their codes backend as well but are unable to detect any further issues as well.

**Issue 2:**
![Issue 2](https://user-images.githubusercontent.com/75086091/112787620-7e5fe600-908b-11eb-903b-d72da305f277.png)

**Client's comment:**
Please clarify which edit field AIFA is pointing to. The edit area only comes out after we tap on the search icon. Hence, the current view should suffice. 

**(Daphne's additional notes to Microsoft: We have scanned the page when the edit textbox should appear only to encounter the same error)**
![Issue 3](https://user-images.githubusercontent.com/75086091/112787657-9c2d4b00-908b-11eb-9f60-4b077a2129b8.png)

**Questions on next steps for both Issues 1 & 2**
Initially, we advised the client's developers to check their codes backend for any WCAG issues since it was not detectable by Accessibility Insights. The client's developer had since done so but is unable to identify any issues. 

1) Since we are unable to advise on the location of the issue flagged, please advise on the next step on what should be done on the developer's end to troubleshoot the issue and rectify the WCAG error flagged? 

2) Just because a view is not visible, is it safe to assume that users who rely on accessibility tools will not be affected despite WCAG issue being flagged by Accessibility Insights?

Unfortunately, we are unable to share the login details of this mobile app as private confidential is required.

Greatly appreciate your response. Thank you!

**Comment by DaveTryon** [comment]
Thanks, @daphneytt, we'll start investigating from our end. Is it possible to get access to the application being tested, so that we can work with live data instead of just screenshots?

**Comment by daphneyyt** [comment]
Hi @DaveTryon thank you for responding! Unfortunately, I won't be able to pass you the application because personal information is required to access the app's content. Would your team be able to advise on the next steps based on the screenshots provided, please?

**Comment by DaveTryon** [comment]
@daphneyyt, the "highlight unavailable" status most commonly indicates a View that exists on the page, but is outside of the current display viewport. Your samples both include scrollable lists (based on the thumb on the right side of the page), so if this is actually caused by being offscreen, you just need to scroll down the page until more Views are in the display viewport, then press the _Start over_ button in the top right corner of the app. This will rescan the page with an updated display viewport and if the View is contained in the updated viewport, it should be possible to identify it in the screenshot. Based on the size of the scroll thumb, you may need to try 3 or 4 scroll positions to be sure that the display viewport has included all Views on the page.

It might seem a bit counterintuitive to scan Views that are outside the display viewport, but it makes tremendous sense in the accessibility space. A low vision user, for example, might be using a high magnification that leaves a very small display viewport, but still wants to be able to navigate the page. The Android accessibility tree includes all Views on the page, so users of assistive technologies can learn about _everything_ on the page in ways that aren't constrained by the size of the display viewport.

Please let us know if this gets you unstuck. The next option would be to query the service directly and manually try to identify the View from the JSON that gets returned, but that requires a deep understanding of how the JSON is structured, and represents a lot more effort than scrolling and rescanning.

**Comment by daphneyyt** [comment]
Hi @DaveTryon thank you very much for the response. At this point, I don't think we are able to link Microsoft up with the app owner. We will let you know if there are any updates. Thank you for your help!
